###
GET  http://localhost:8000/auth/

###
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "nwosu nonso",
    "email": "louisnwosu94@gmail.com",
    "password": "ilovewanking"
}
 